In [1]:
import pandas as pd

In [2]:
rules = pd.read_csv('../results/s4_c03_t5_m30.csv')

In [3]:
rules.shape

(2527, 5)

In [4]:
rules

,Unnamed: 0,antecedent,consequent,confidence,lift
0,0,['23007'],['22551'],0.500000,5.952381
1,1,['22423'],['POST'],0.400000,0.985222
2,2,['23167'],['22720'],0.500000,6.756757
3,3,['23112'],['22423'],0.666667,5.128205
4,4,['20675'],['21238'],0.307692,13.986014
...,...,...,...,...,...
2522,2522,"['23289', '23290', '22629', '23292', '23291']",['22630'],1.000000,9.803922
2523,2523,"['POST', '22631']","['22328', '22326', '22630', '22629']",0.307692,17.094017
2524,2524,"['22328', 'POST', '22631']","['22326', '22630', '22629']",0.666667,16.666667
2525,2525,"['22328', '22326', 'POST', '22631']","['22630', '22629']",0.666667,9.523810
2526,2526,"['POST', '22631', '22328', '22326', '22629']",['22630'],0.800000,7.843137

In [5]:
import json 
import re

def rules_to_json(rules, path):   

    def filter_fields(dictionary, fields_to_keep):
        return {key: value for key, value in dictionary.items() if key in fields_to_keep}

    filtered_data = [filter_fields(item, ['antecedent', 'consequent', 'lift', 'confidence']) for item in rules]

    json_data = json.dumps(filtered_data, indent=2)
    with open(f'{path}/rules.json', 'w') as json_file:
        json_file.write(json_data)
        json_file.close()
        print("successfully wrote results.")
    

def rules_to_markdown(rules, path):
    rules_file = open(f'{path}/rules.md', 'w')
    line = f"<ol>\n"
    for rule in rules:
        line += f"<li>"
        
        line += f"{rule['antecedent']}"
        
        line += f" ========> "
        
        line += f"{rule['consequent']} "
        line += f"</li>\n"
    line += f"</ol>"
    rules_file.write(line)

    rules_file.close()

def rules_to_xlsx(rules, path):
    pd.DataFrame(rules).to_csv(path)

def map_rules(rules):
    mapping = open("../data/map_stockCode_item.json", "r")
    json_map = json.load(mapping)
    
    cp_rules = rules.copy()
    mapped_rules = []
    for rule in cp_rules:
        ant = []
        for item in rule['antecedent']:
            ant.append(json_map[item])

        cons = []
        for item in rule['consequent']:
            cons.append(json_map[item])

        obj = {'antecedent': ', '.join(ant), 'consequent': ', '.join(cons), 'confidence': rule['confidence'], 'lift': rule['lift']}
        mapped_rules.append(obj)

    return mapped_rules


print("mapping to items...")
set_matplotlib_formatsrules = map_rules(rules)
print("writing to file...")
rules_to_markdown(map_rules, "../results/s4_c03_t5_m30.md")
rules_to_json(map_rules, "../results/s4_c03_t5_m30.json")
rules_to_xlsx(map_rules, '../results/s4_c03_t5_m30.xlsx')
rules

mapping to items...

TypeError: string indices must be integers